2022-05-25 14:31:27,233 ERROR: Exception on /word/4 [PUT] [in /Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/app/routes.py", line 113, in update_word
    return jsonify(word.json_str())
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/app/models.py", line 52, in json_str
    return '{"id": "{}"}'.format(self.id)
KeyError: '"id"'
2022-05-25 14:31:49,262 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 14:34:03,476 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 14:37:09,721 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 14:42:09,132 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 14:49:40,271 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 14:49:59,895 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 14:50:17,298 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 14:50:25,423 ERROR: Exception on /actual_words [GET] [in /Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/app/routes.py", line 119, in actual_words
    return jsonify(today_added_words())
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/json/__init__.py", line 301, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Word is not JSON serializable
2022-05-25 14:51:46,267 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 14:39:32,615 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 14:40:20,164 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 14:40:59,355 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 14:41:40,750 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 14:43:00,411 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 14:43:09,446 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 14:46:14,267 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 14:49:33,978 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 15:01:57,951 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 15:25:33,971 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 15:26:56,038 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 15:28:45,297 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 15:29:17,637 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 15:33:52,514 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 15:38:39,738 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 15:40:21,597 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 15:50:44,925 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 15:52:43,617 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 15:54:47,968 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 15:56:11,756 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 16:13:57,128 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 16:14:15,672 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 16:15:35,974 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 16:24:20,866 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 16:25:37,866 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 16:30:44,955 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 16:31:00,978 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 16:32:44,640 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 16:35:44,909 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-26 16:39:34,262 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
