2022-05-24 17:29:09,937 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-24 17:33:46,918 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-24 17:34:33,170 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-24 17:43:08,312 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-24 17:47:36,328 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 09:24:52,286 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 10:03:46,345 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 10:03:55,836 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 10:05:10,965 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 10:07:14,553 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 10:27:02,107 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 10:27:10,841 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 10:27:20,951 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 10:27:32,472 ERROR: Exception on /word/1 [GET] [in /Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/app/routes.py", line 61, in get_word
    'body': word.body,
AttributeError: 'BaseQuery' object has no attribute 'body'
2022-05-25 10:28:06,443 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 10:28:09,539 ERROR: Exception on /word/1 [GET] [in /Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/app/routes.py", line 56, in get_word
    word = Word.query.get(id=word_id)
TypeError: get() got an unexpected keyword argument 'id'
2022-05-25 10:28:26,918 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 10:29:18,438 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 10:29:55,818 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 10:31:08,495 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 10:57:10,403 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 10:58:21,795 ERROR: Exception on /word [POST] [in /Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'add_word' did not return a valid response. The function either returned None or ended without a return statement.
2022-05-25 10:58:51,121 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 10:59:18,057 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 11:00:18,192 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 11:00:42,380 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 11:00:48,045 ERROR: Exception on /word [POST] [in /Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/app/routes.py", line 74, in add_word
    return jsonify(request)
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/json/__init__.py", line 301, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/dmitriy/Code/tinkoff_5_letter_word/env/lib/python3.8/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Request is not JSON serializable
2022-05-25 11:01:39,103 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 11:02:00,743 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 11:11:49,113 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 11:14:23,195 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 11:17:16,781 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 11:17:47,733 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 11:19:25,742 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 11:23:26,531 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 11:25:31,496 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 11:26:41,047 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 11:38:31,810 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 11:40:19,275 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 11:41:19,469 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 11:44:08,278 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 11:44:37,026 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
2022-05-25 11:48:21,417 INFO: Five letters app startup [in /Users/dmitriy/Code/tinkoff_5_letter_word/app/__init__.py:28]
